- set_fact:
    homebrew: {}

- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: install cask applications
  homebrew_cask:
    name:            '{{ item.name | default(item) }}'
    state:           '{{ item.state | default("present") }}'
    install_options: '{{ item.install_options | default("") }}'
  with_items: '{{ homebrew.applications }}'
  when: homebrew.applications

- name: install homebrew packages
  homebrew:
    name:            '{{ item.name | default(item) }}'
    state:           '{{ item.state | default("present") }}'
    install_options: '{{ item.install_options | default("") }}'
  with_items: '{{ homebrew.packages }}'
  when: homebrew.packages

- name: install npm packages globally
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{ homebrew.npm_packages }}'
  when: homebrew.npm_packages

- name: install Python packages globally
  pip:
    name: '{{ item }}'
    executable: pip3
  with_items: '{{ homebrew.python_packages }}'
  when: homebrew.python_packages

- name: install Go packages globally
  shell: go install {{ item }}
  with_items: '{{ homebrew.go_packages }}'
  when: homebrew.go_packages
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ home_path }}/.asdf/shims"
