asdf:
  dir:  '{{ home_path }}/.asdf'}}

homebrew: 
  applications:
    - adoptopenjdk8
    - adoptopenjdk15
    - alfred
    - android-studio
    - appcleaner
    - bettertouchtool
    - biscuit
    - clipy
    - docker
    - flux
    - google-chrome
    - google-japanese-ime
    - hyperswitch
    - iterm2
    - jetbrains-toolbox
    - kap
    - karabiner-elements
    - kindle
    - kitematic
    - macs-fan-control
    - miro
    - mysqlworkbench
    - postman
    - pushplaylabs-sidekick
    - rstudio
    - sequel-ace
    - ShowyEdge
    - typora
    - xmind
    - xquartz
    - vanilla
    - visual-studio-code
    - zoom

  packages:
    - automake
    - carthage
    - cocoapods
    - direnv
    - docker
    - ffmpeg
    - gawk
    - gibo
    - git
    - git-delta
    - git-flow
    - htop
    - jpeg
    - krew
    - kubectl
    - lazygit
    - mecab
    - minikube
    - mycli
    - mysql@5.7
    - nkf
    - nvim
    - pandoc
    - peco
    - r
    - rename
    - sbt
    - sox
    - tmux
    - translate-shell
    - trash
    - tree
    - vim
    - watch
    - wget

link:
  zsh/.zshrc:                 .zshrc
  zsh/.zshenv:                .zshenv
  zsh/.zprofile:              .zprofile
  bash/.bash_profile:         .bash_profile
  bash/.bashrc:               .bashrc
  bash/local.bash:            local.bash
  bash/common.bash:           common.bash
  config/.ansible.cfg:        .ansible.cfg
  config/.aws/config:         .aws/config
  git/.gitconfig:             .gitconfig
  git/.gitignore:             .gitignore
  ide/.ideavimrc:             .ideavimrc
  vim/.vimrc:                 .vimrc
  tmux/.tmux.conf:            .tmux.conf
  karabiner:                  .config/karabiner
  fish:                       .config/fish
  nvim:                       .config/nvim
  spaceship:                  .config/spaceship
