anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

homebrew:
  applications:
    - adoptopenjdk8
    - alfred
    - amazon-music
    - android-studio
    - appcleaner
    - bettertouchtool
    - docker
    - clipy
    - flux
    - google-chrome
    - google-backup-and-sync
    - google-japanese-ime
    - hyperswitch
    - iterm2
    - jetbrains-toolbox
    - kap
    - karabiner-elements
    - kindle
    - macs-fan-control
    - mathpix-snipping-tool
    - mysqlworkbench
    - postman
    - station
    - ShowyEdge
    - xquartz
    - vagrant
    - vanilla
    - visual-studio-code

  packages:
    - automake
    - carthage
    - cocoapods
    - docker
    - fish
    - ffmpeg
    - gawk
    - git
    - git-flow
    - htop
    - jpeg
    - mecab
    - mycli
    - mysql@5.7
    - nkf
    - pandoc
    - peco
    - r
    - rename
    - rmtrash
    - sbt
    - sox
    - tmux
    - translate-shell
    - tree
    - vim
    - wget

ruby:
  versions:
    - '2.5.1'
  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'
  plugins:
    - ianheggie/rbenv-binstubs
    - sstephenson/rbenv-default-gems
    - sstephenson/rbenv-gem-rehash

nodejs:
  versions:
    - "v8.11.3"

golang:
  versions:
    - "1.10.0"

python:
  versions:
    - '3.7.0'

  packages:
    - vim-vint

java:
  versions:
    - '1.8'

link:
  bash/.bash_profile:         .bash_profile
  bash/.bashrc:               .bashrc
  bash/local.bash:            local.bash
  bash/common.bash:           common.bash
  config/.ansible.cfg:        .ansible.cfg
  config/.aws/config:         .aws/config
  git/.gitconfig:             .gitconfig
  git/.gitignore:             .gitignore
  ide/.ideavimrc:             .ideavimrc
  vim/.vimrc:                 .vimrc
  tmux/.tmux.conf:            .tmux.conf
  karabiner:                  .config/karabiner
  fish:                       .config/fish
