anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

homebrew:
  applications:
    - alfred
	- android-studio
	- appcleaner
	- bettertouchtool
	- docker
	- clipmenu
	- flux
	- franz
	- google-chrome
	- google-drive
	- google-japanese-ime
	- hyperswitch
	- iterm2
    - jetbrains-toolbox
	- kap
	- karabiner
	- kindle
	- r
	- vanilla

  packages:
    - automake
	- carthage
	- cocoapods
	- docker
	- fish
	- gcc
	- git
	- git-flow
	- gradle
	- jpeg
	- mecab
	- mycli
	- nkf
	- peco
	- rmtrash
	- sox
	- tmux
	- tree
	- wget

ruby:
  versions:
    - '2.5.1'
  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'
  plugins:
    - ianheggie/rbenv-binstubs
    - sstephenson/rbenv-default-gems
    - sstephenson/rbenv-gem-rehash

python:
  versions:
    - '3.7.0'

  packages:
    - vim-vint

link:
  bash/.bash_profile:         .bash_profile
  bash/.bashrc:               .bashrc
  bash/local.bash:            local.bash
  bash/common.bash:           common.bash
  config/.ansible.cfg:        .ansible.cfg
  config/.aws/config:         .aws/config
  git/.gitconfig:             .gitconfig
  git/.gitignore:             .gitignore
  vim/.vimrc:                 .vimrc
  tmux/.tmux.conf:            .tmux.conf
  karabiner:                  .config/karabiner
  fish:                       .config/fish
