- name:       hiramekun's development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    ansible_python_interpreter: /usr/bin/python3

  roles:
    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'link']

    # install 
    #-----------------------------------------------
    - role: asdf
      tags: ['install', 'asdf']
    - role: homebrew
      tags: ['install', 'homebrew']
    - role: vim
      tags: ['app', 'vim']

